// eolymp-shapes.h 2.3.0 — test shapes for eolymp.h generators.
// https://github.com/eolymp/h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eolymp Academy LLC
//
// Trees, graphs, sequences, strings and points, with the relabelling and
// shuffling a generator must not forget. Include it after eolymp.h; the judge's
// C++ runtime carries both files.
//
// Generated from src/shapes/ by tools/amalgamate.py. Do not edit this file.


#ifndef EOLYMP_SHAPES_H_INCLUDED
#define EOLYMP_SHAPES_H_INCLUDED

#include "eolymp.h"

#if (defined(_MSVC_LANG) ? _MSVC_LANG : __cplusplus) >= 201703L

#if defined(_MSC_VER) && defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable : 4996)
#endif

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

namespace eo {

struct graph {
    int n;
    std::vector<edge> edges;
    bool directed;
};

namespace shapes {
namespace detail {

inline void at_least(int n, int least, char const* what) {
    if (n < least) eo::detail::library_error(fmt("{} needs at least {} vertices, not {}", what, least, n));
}

inline graph undirected(int n, std::vector<edge> edges) { return graph{n, std::move(edges), false}; }

inline void still_trying(long long& tries, long long most, char const* what) {
    if (++tries <= most) return;
    eo::detail::library_error(
        fmt("{} did not come out in {} attempts; ask for fewer, or build it another way", what, most));
}

inline void kept_of(long long kept, long long tries, char const* what, eo::detail::site where) {
    if (tries <= 1000 || tries <= 4 * kept) return;
    eo::detail::warn("EO505", fmt("{} kept {} of {} draws", what, kept, tries),
                     "most draws were thrown away; ask for fewer, or build it another way", where);
}

}  // namespace detail

[[nodiscard]] inline std::vector<edge> presented(rng& draw, graph const& made) {
    std::vector<int> const labels = draw.perm(made.n, 1);
    std::vector<edge> shown;
    shown.reserve(made.edges.size());
    for (edge const& one : made.edges) {
        int const u = labels[static_cast<std::size_t>(one.u) - 1];
        int const v = labels[static_cast<std::size_t>(one.v) - 1];
        bool const turn = !made.directed && draw.chance(0.5);
        shown.push_back(turn ? edge{v, u} : edge{u, v});
    }
    draw.shuffle(shown);
    return shown;
}

[[nodiscard]] inline std::vector<int> parent_array(rng& draw, graph const& made, int root = 1) {
    detail::at_least(made.n, 1, "a parent array");
    if (root < 1 || root > made.n)
        eo::detail::library_error(fmt("the root is {}, outside 1..{}", root, made.n));
    std::vector<std::vector<int>> neighbours(static_cast<std::size_t>(made.n) + 1);
    for (edge const& one : made.edges) {
        neighbours[static_cast<std::size_t>(one.u)].push_back(one.v);
        neighbours[static_cast<std::size_t>(one.v)].push_back(one.u);
    }
    std::vector<int> label(static_cast<std::size_t>(made.n) + 1, 0);
    std::vector<int> came_from(static_cast<std::size_t>(made.n) + 1, 0);
    std::vector<int> waiting{root};
    label[static_cast<std::size_t>(root)] = 1;
    int given = 1;
    while (!waiting.empty()) {
        int const here = waiting.back();
        waiting.pop_back();
        std::vector<int> children;
        for (int const other : neighbours[static_cast<std::size_t>(here)])
            if (other != came_from[static_cast<std::size_t>(here)]) children.push_back(other);
        draw.shuffle(children);
        for (int const other : children) {
            came_from[static_cast<std::size_t>(other)] = here;
            label[static_cast<std::size_t>(other)] = ++given;
            waiting.push_back(other);
        }
    }
    if (given != made.n)
        eo::detail::library_error(fmt("a parent array needs a tree; {} of {} vertices were reached from {}",
                                      given, made.n, root));
    std::vector<int> parents(static_cast<std::size_t>(made.n) - 1, 0);
    for (int vertex = 1; vertex <= made.n; vertex++)
        if (vertex != root)
            parents[static_cast<std::size_t>(label[static_cast<std::size_t>(vertex)]) - 2] =
                label[static_cast<std::size_t>(came_from[static_cast<std::size_t>(vertex)])];
    return parents;
}

}  // namespace shapes
}  // namespace eo

namespace eo {
namespace shapes {

[[nodiscard]] inline graph random_tree(rng& draw, int n) {
    detail::at_least(n, 1, "a tree");
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++)
        edges.push_back(edge{static_cast<int>(draw.uniform(1, vertex - 1)), vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph deep_tree(rng& draw, int n, int lean) {
    detail::at_least(n, 1, "a tree");
    if (lean < 0) eo::detail::library_error(fmt("deep_tree leans toward the last vertex; {} is below 0", lean));
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++)
        edges.push_back(edge{static_cast<int>(draw.weighted(1, vertex - 1, lean)), vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph uniform_tree(rng& draw, int n) {
    detail::at_least(n, 1, "a tree");
    if (n <= 2) {
        std::vector<edge> edges;
        if (n == 2) edges.push_back(edge{1, 2});
        return detail::undirected(n, std::move(edges));
    }
    std::vector<int> code;
    std::vector<int> degree(static_cast<std::size_t>(n) + 1, 1);
    for (int at = 0; at < n - 2; at++) {
        int const chosen = static_cast<int>(draw.uniform(1, n));
        code.push_back(chosen);
        degree[static_cast<std::size_t>(chosen)]++;
    }
    std::vector<edge> edges;
    int lowest = 1;
    while (degree[static_cast<std::size_t>(lowest)] != 1) lowest++;
    int leaf = lowest;
    for (int const chosen : code) {
        edges.push_back(edge{leaf, chosen});
        if (--degree[static_cast<std::size_t>(chosen)] == 1 && chosen < lowest) {
            leaf = chosen;
        } else {
            lowest++;
            while (degree[static_cast<std::size_t>(lowest)] != 1) lowest++;
            leaf = lowest;
        }
    }
    edges.push_back(edge{leaf, n});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph path(int n) {
    detail::at_least(n, 1, "a path");
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++) edges.push_back(edge{vertex - 1, vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph star(int n) {
    detail::at_least(n, 1, "a star");
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++) edges.push_back(edge{1, vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph caterpillar(rng& draw, int n, int spine = 0) {
    detail::at_least(n, 1, "a caterpillar");
    int const along = spine > 0 ? spine : (n + 1) / 2;
    if (along > n) eo::detail::library_error(fmt("a spine of {} does not fit {} vertices", along, n));
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= along; vertex++) edges.push_back(edge{vertex - 1, vertex});
    for (int vertex = along + 1; vertex <= n; vertex++)
        edges.push_back(edge{static_cast<int>(draw.uniform(1, along)), vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph broom(int n, int handle = 0) {
    detail::at_least(n, 1, "a broom");
    int const along = handle > 0 ? handle : (n + 1) / 2;
    if (along > n) eo::detail::library_error(fmt("a handle of {} does not fit {} vertices", along, n));
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= along; vertex++) edges.push_back(edge{vertex - 1, vertex});
    for (int vertex = along + 1; vertex <= n; vertex++) edges.push_back(edge{along, vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph kary_tree(int n, int k) {
    detail::at_least(n, 1, "a k-ary tree");
    if (k < 1) eo::detail::library_error(fmt("a k-ary tree branches at least once; k is {}", k));
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++) edges.push_back(edge{(vertex - 2) / k + 1, vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph binary_tree(int n) { return kary_tree(n, 2); }

[[nodiscard]] inline graph dumbbell(int n) {
    detail::at_least(n, 1, "a dumbbell");
    std::vector<edge> edges;
    if (n >= 2) edges.push_back(edge{1, 2});
    int const near_one = n / 2;
    for (int vertex = 3; vertex <= n; vertex++) edges.push_back(edge{vertex <= near_one + 1 ? 1 : 2, vertex});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph spider(int n, int legs) {
    detail::at_least(n, 1, "a spider");
    if (legs < 1) eo::detail::library_error(fmt("a spider has at least one leg, not {}", legs));
    std::vector<edge> edges;
    int next = 2;
    for (int leg = 0; leg < legs && next <= n; leg++) {
        int const length = (n - 1) / legs + (leg < (n - 1) % legs ? 1 : 0);
        int attach = 1;
        for (int step = 0; step < length; step++) {
            edges.push_back(edge{attach, next});
            attach = next++;
        }
    }
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph tree(rng& draw, int n, std::string const& shape) {
    if (shape == "random") return random_tree(draw, n);
    if (shape == "uniform") return uniform_tree(draw, n);
    if (shape == "path") return path(n);
    if (shape == "star") return star(n);
    if (shape == "caterpillar") return caterpillar(draw, n);
    if (shape == "broom") return broom(n);
    if (shape == "binary") return binary_tree(n);
    if (shape == "dumbbell") return dumbbell(n);
    eo::detail::library_error(
        fmt("\"{}\" is not a tree shape; the names are random, uniform, path, star, caterpillar, broom, "
            "binary and dumbbell",
            shape));
}

}  // namespace shapes
}  // namespace eo

namespace eo {
namespace shapes {
namespace detail {

inline long long pairs_of(int n) {
    return static_cast<long long>(n) * static_cast<long long>(n - 1) / 2;
}

inline void room_for(int n, long long m, long long least, char const* what) {
    at_least(n, 1, what);
    long long const most = pairs_of(n);
    if (m < least || m > most)
        eo::detail::library_error(
            fmt("{} on {} vertices has {}..{} edges, not {}", what, n, least, most, m));
}

class pair_set {
public:
    explicit pair_set(std::size_t most) {
        while ((std::size_t{1} << bits_) < 2 * most + 2) bits_++;
        slots_.assign(std::size_t{1} << bits_, empty);
    }

    bool insert(int u, int v) {
        std::uint64_t const key = pack(u, v);
        std::size_t at = home(key);
        while (slots_[at] != empty) {
            if (slots_[at] == key) return false;
            at = (at + 1) & (slots_.size() - 1);
        }
        slots_[at] = key;
        return true;
    }

    bool contains(int u, int v) const {
        std::uint64_t const key = pack(u, v);
        for (std::size_t at = home(key); slots_[at] != empty; at = (at + 1) & (slots_.size() - 1))
            if (slots_[at] == key) return true;
        return false;
    }

private:
    static std::uint64_t constexpr empty = ~std::uint64_t{0};

    static std::uint64_t pack(int u, int v) {
        return (static_cast<std::uint64_t>(static_cast<std::uint32_t>(u)) << 32) | static_cast<std::uint32_t>(v);
    }

    std::size_t home(std::uint64_t key) const {
        return static_cast<std::size_t>((key * 0x9e3779b97f4a7c15ull) >> (64 - bits_));
    }

    int bits_ = 4;
    std::vector<std::uint64_t> slots_;
};

inline std::vector<edge> filled_sparsely(rng& draw, int n, long long m, std::vector<edge> have) {
    pair_set seen(static_cast<std::size_t>(m));
    for (edge const& one : have) seen.insert((std::min)(one.u, one.v), (std::max)(one.u, one.v));
    long long const given = static_cast<long long>(have.size());
    long long tries = 0;
    long long const most = 32 * m + 1000;
    while (static_cast<long long>(have.size()) < m) {
        still_trying(tries, most, "a graph with that many edges");
        int const u = static_cast<int>(draw.uniform(1, n));
        int const v = static_cast<int>(draw.uniform(1, n));
        if (u == v) continue;
        if (!seen.insert((std::min)(u, v), (std::max)(u, v))) continue;
        have.push_back(edge{u, v});
    }
    kept_of(m - given, tries, "a graph with that many edges", eo::detail::site::here());
    return have;
}

inline std::vector<edge> filled_densely(rng& draw, int n, long long m, std::vector<edge> have) {
    pair_set seen(have.size());
    for (edge const& one : have) seen.insert((std::min)(one.u, one.v), (std::max)(one.u, one.v));
    std::vector<edge> spare;
    for (int u = 1; u <= n; u++)
        for (int v = u + 1; v <= n; v++)
            if (!seen.contains(u, v)) spare.push_back(edge{u, v});
    draw.shuffle(spare);
    for (edge const& one : spare) {
        if (static_cast<long long>(have.size()) >= m) break;
        have.push_back(one);
    }
    return have;
}

inline std::vector<edge> filled(rng& draw, int n, long long m, std::vector<edge> have) {
    if (m * 4 > pairs_of(n)) return filled_densely(draw, n, m, std::move(have));
    return filled_sparsely(draw, n, m, std::move(have));
}

}  // namespace detail

[[nodiscard]] inline graph connected_graph(rng& draw, int n, long long m) {
    detail::room_for(n, m, static_cast<long long>(n) - 1, "a connected graph");
    graph made = random_tree(draw, n);
    made.edges = detail::filled(draw, n, m, std::move(made.edges));
    return made;
}

[[nodiscard]] inline graph sparse_graph(rng& draw, int n, long long m) {
    detail::room_for(n, m, 0, "a graph");
    return detail::undirected(n, detail::filled(draw, n, m, {}));
}

[[nodiscard]] inline graph complete_graph(int n) {
    detail::at_least(n, 1, "a complete graph");
    std::vector<edge> edges;
    for (int u = 1; u <= n; u++)
        for (int v = u + 1; v <= n; v++) edges.push_back(edge{u, v});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph cycle(int n) {
    detail::at_least(n, 3, "a cycle");
    std::vector<edge> edges;
    for (int vertex = 2; vertex <= n; vertex++) edges.push_back(edge{vertex - 1, vertex});
    edges.push_back(edge{n, 1});
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph cycle_with_chords(rng& draw, int n, long long chords) {
    detail::at_least(n, 3, "a cycle");
    long long const m = static_cast<long long>(n) + chords;
    detail::room_for(n, m, n, "a cycle with chords");
    graph made = cycle(n);
    made.edges = detail::filled(draw, n, m, std::move(made.edges));
    return made;
}

[[nodiscard]] inline graph grid(int rows, int columns) {
    if (rows < 1 || columns < 1)
        eo::detail::library_error(fmt("a grid is at least 1 by 1, not {} by {}", rows, columns));
    auto const at = [columns](int row, int column) { return (row - 1) * columns + column; };
    std::vector<edge> edges;
    for (int row = 1; row <= rows; row++)
        for (int column = 1; column <= columns; column++) {
            if (column < columns) edges.push_back(edge{at(row, column), at(row, column + 1)});
            if (row < rows) edges.push_back(edge{at(row, column), at(row + 1, column)});
        }
    return detail::undirected(rows * columns, std::move(edges));
}

[[nodiscard]] inline graph bipartite_graph(rng& draw, int left, int right, long long m) {
    if (left < 1 || right < 1)
        eo::detail::library_error(fmt("a bipartite graph has sides of at least 1, not {} and {}", left, right));
    long long const most = static_cast<long long>(left) * static_cast<long long>(right);
    if (m < 0 || m > most)
        eo::detail::library_error(fmt("{} by {} holds 0..{} edges, not {}", left, right, most, m));
    std::vector<edge> edges;
    if (m * 4 > most) {
        std::vector<edge> spare;
        for (int u = 1; u <= left; u++)
            for (int v = 1; v <= right; v++) spare.push_back(edge{u, left + v});
        draw.shuffle(spare);
        spare.resize(static_cast<std::size_t>(m));
        edges = std::move(spare);
    } else {
        detail::pair_set seen(static_cast<std::size_t>(m));
        long long tries = 0;
        long long const ceiling = 32 * m + 1000;
        while (static_cast<long long>(edges.size()) < m) {
            detail::still_trying(tries, ceiling, "a bipartite graph with that many edges");
            int const u = static_cast<int>(draw.uniform(1, left));
            int const v = static_cast<int>(draw.uniform(1, right));
            if (!seen.insert(u, v)) continue;
            edges.push_back(edge{u, left + v});
        }
        detail::kept_of(m, tries, "a bipartite graph with that many edges", eo::detail::site::here());
    }
    return detail::undirected(left + right, std::move(edges));
}

[[nodiscard]] inline graph complete_bipartite(int left, int right) {
    if (left < 1 || right < 1)
        eo::detail::library_error(fmt("a bipartite graph has sides of at least 1, not {} and {}", left, right));
    std::vector<edge> edges;
    for (int u = 1; u <= left; u++)
        for (int v = 1; v <= right; v++) edges.push_back(edge{u, left + v});
    return detail::undirected(left + right, std::move(edges));
}

[[nodiscard]] inline graph many_components(rng& draw, int n, int pieces) {
    detail::at_least(n, 1, "a graph");
    if (pieces < 1 || pieces > n)
        eo::detail::library_error(fmt("{} vertices fall into 1..{} pieces, not {}", n, n, pieces));
    std::vector<long long> const sizes = draw.partition(pieces, n);
    std::vector<edge> edges;
    int first = 1;
    for (long long const size : sizes) {
        graph const piece = random_tree(draw, static_cast<int>(size));
        for (edge const& one : piece.edges) edges.push_back(edge{one.u + first - 1, one.v + first - 1});
        first += static_cast<int>(size);
    }
    return detail::undirected(n, std::move(edges));
}

[[nodiscard]] inline graph dag(rng& draw, int n, long long m) {
    detail::room_for(n, m, 0, "a dag");
    std::vector<int> const order = draw.perm(n, 1);
    std::vector<edge> edges;
    if (m * 4 > detail::pairs_of(n)) {
        std::vector<edge> spare;
        for (int i = 0; i < n; i++)
            for (int j = i + 1; j < n; j++)
                spare.push_back(edge{order[static_cast<std::size_t>(i)], order[static_cast<std::size_t>(j)]});
        draw.shuffle(spare);
        spare.resize(static_cast<std::size_t>(m));
        edges = std::move(spare);
    } else {
        detail::pair_set seen(static_cast<std::size_t>(m));
        long long tries = 0;
        long long const most = 32 * m + 1000;
        while (static_cast<long long>(edges.size()) < m) {
            detail::still_trying(tries, most, "a dag with that many edges");
            int const i = static_cast<int>(draw.uniform(0, n - 2));
            int const j = static_cast<int>(draw.uniform(i + 1, n - 1));
            if (!seen.insert(i, j)) continue;
            edges.push_back(edge{order[static_cast<std::size_t>(i)], order[static_cast<std::size_t>(j)]});
        }
        detail::kept_of(m, tries, "a dag with that many edges", eo::detail::site::here());
    }
    return graph{n, std::move(edges), true};
}

[[nodiscard]] inline std::vector<int> functional(rng& draw, int n, std::string const& shape) {
    detail::at_least(n, 1, "a functional graph");
    std::vector<int> next(static_cast<std::size_t>(n) + 1, 0);
    std::vector<int> const order = draw.perm(n, 1);
    auto const along = [&](int from, int to) {
        for (int at = from; at < to; at++)
            next[static_cast<std::size_t>(order[static_cast<std::size_t>(at)])] =
                order[static_cast<std::size_t>(at) + 1];
    };
    if (shape == "cycle") {
        along(0, n - 1);
        next[static_cast<std::size_t>(order[static_cast<std::size_t>(n) - 1])] =
            order[0];
    } else if (shape == "rho") {
        int const tail = n > 1 ? static_cast<int>(draw.uniform(1, n - 1)) : 0;
        along(0, n - 1);
        next[static_cast<std::size_t>(order[static_cast<std::size_t>(n) - 1])] =
            order[static_cast<std::size_t>(tail)];
    } else if (shape == "self") {
        for (int vertex = 1; vertex <= n; vertex++) next[static_cast<std::size_t>(vertex)] = vertex;
    } else if (shape == "random") {
        for (int vertex = 1; vertex <= n; vertex++)
            next[static_cast<std::size_t>(vertex)] = static_cast<int>(draw.uniform(1, n));
    } else {
        eo::detail::library_error(
            fmt("\"{}\" is not a functional shape; the names are cycle, rho, self and random", shape));
    }
    next.erase(next.begin());
    return next;
}

}  // namespace shapes
}  // namespace eo

namespace eo {
namespace shapes {
namespace detail {

inline void room_for_values(long long count, long long low, long long high, char const* what) {
    if (count < 0) eo::detail::library_error(fmt("{} has at least no elements, not {}", what, count));
    if (low > high) eo::detail::library_error(fmt("{} draws from {}..{}, which is empty", what, low, high));
}

inline long long width_of(long long low, long long high) {
    unsigned long long const span = static_cast<unsigned long long>(high) - static_cast<unsigned long long>(low);
    return span > 9223372036854775807ull ? 9223372036854775807LL : static_cast<long long>(span);
}

inline int decimal_length(long long value) {
    int length = 1;
    for (; value >= 10; value /= 10) length++;
    return length;
}

}  // namespace detail

[[nodiscard]] inline std::vector<long long> equal_values(long long count, long long value) {
    detail::room_for_values(count, value, value, "a plateau");
    return std::vector<long long>(static_cast<std::size_t>(count), value);
}

[[nodiscard]] inline std::vector<long long> few_distinct(rng& draw, long long count, long long kinds,
                                                         long long low, long long high) {
    detail::room_for_values(count, low, high, "a sequence of few distinct values");
    if (kinds < 1) eo::detail::library_error(fmt("few_distinct needs at least one kind, not {}", kinds));
    std::vector<long long> const chosen = draw.distinct((std::min)(kinds, high - low + 1), low, high);
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++) values.push_back(draw.pick(chosen));
    return values;
}

[[nodiscard]] inline std::vector<long long> plateaus(rng& draw, long long count, long long runs,
                                                     long long low, long long high) {
    detail::room_for_values(count, low, high, "a sequence of plateaus");
    if (runs < 1 || runs > count)
        eo::detail::library_error(fmt("{} elements fall into 1..{} runs, not {}", count, count, runs));
    std::vector<long long> const lengths = draw.partition(runs, count);
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long const length : lengths) {
        long long const value = draw.uniform(low, high);
        for (long long at = 0; at < length; at++) values.push_back(value);
    }
    return values;
}

[[nodiscard]] inline std::vector<long long> nearly_sorted(rng& draw, long long count, long long low,
                                                          long long high, long long swaps) {
    detail::room_for_values(count, low, high, "a nearly sorted sequence");
    if (swaps < 0) eo::detail::library_error(fmt("nearly_sorted makes at least no swaps, not {}", swaps));
    std::vector<long long> values = draw.ints(count, low, high);
    std::sort(values.begin(), values.end());
    for (long long at = 0; at < swaps && count >= 2; at++) {
        std::size_t const one = static_cast<std::size_t>(draw.uniform(0, count - 1));
        std::size_t const other = static_cast<std::size_t>(draw.uniform(0, count - 1));
        std::swap(values[one], values[other]);
    }
    return values;
}

[[nodiscard]] inline std::vector<long long> alternating(rng& draw, long long count, long long low,
                                                        long long high) {
    detail::room_for_values(count, low, high, "an alternating sequence");
    long long const middle = low + (high - low) / 2;
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++)
        values.push_back(at % 2 == 0 ? draw.uniform(low, middle) : draw.uniform(middle, high));
    return values;
}

[[nodiscard]] inline std::vector<long long> hash_collisions(long long count, long long buckets = 107897) {
    if (count < 0) eo::detail::library_error(fmt("hash_collisions makes at least no values, not {}", count));
    if (buckets < 1) eo::detail::library_error(fmt("hash_collisions needs a bucket count, not {}", buckets));
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long at = 1; at <= count; at++) values.push_back(at * buckets);
    return values;
}

[[nodiscard]] inline std::vector<long long> log_uniform(rng& draw, long long count, long long low, long long high) {
    detail::room_for_values(count, low, high, "a log-uniform sequence");
    if (low < 0) eo::detail::library_error(fmt("log_uniform draws from 0 up; {}..{} reaches below it", low, high));
    std::vector<long long> powers{1};
    while (powers.size() < 19) powers.push_back(powers.back() * 10);
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++) {
        std::size_t const length = static_cast<std::size_t>(
            draw.uniform(detail::decimal_length(low), detail::decimal_length(high)));
        long long const shortest = length == 1 ? 0 : powers[length - 1];
        long long const longest = length == 19 ? high : powers[length] - 1;
        values.push_back(draw.uniform((std::max)(low, shortest), (std::min)(high, longest)));
    }
    return values;
}

[[nodiscard]] inline std::vector<long long> near_bounds(rng& draw, long long count, long long low, long long high,
                                                        long long spread) {
    detail::room_for_values(count, low, high, "a sequence near its bounds");
    if (spread < 0)
        eo::detail::library_error(
            fmt("near_bounds keeps within a spread of at least 0 of a bound, not {}", spread));
    long long const reach = (std::min)(spread, detail::width_of(low, high));
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++)
        values.push_back(draw.chance(0.5) ? draw.uniform(low, low + reach) : draw.uniform(high - reach, high));
    return values;
}

[[nodiscard]] inline std::vector<long long> spikes(rng& draw, long long count, long long tall, long long low,
                                                   long long high) {
    detail::room_for_values(count, low, high, "a sequence of spikes");
    if (tall < 0 || tall > count)
        eo::detail::library_error(fmt("{} elements hold 0..{} spikes, not {}", count, count, tall));
    long long const band = detail::width_of(low, high) / 16;
    std::vector<bool> raised(static_cast<std::size_t>(count), false);
    for (long long const at : draw.distinct(tall, 0, count - 1)) raised[static_cast<std::size_t>(at)] = true;
    std::vector<long long> values;
    values.reserve(static_cast<std::size_t>(count));
    for (std::size_t at = 0; at < raised.size(); at++)
        values.push_back(raised[at] ? draw.uniform(high - band, high) : draw.uniform(low, low + band));
    return values;
}

[[nodiscard]] inline std::vector<long long> split_sum(rng& draw, long long total, long long parts, long long least,
                                                      long long most) {
    if (parts < 1) eo::detail::library_error(fmt("split_sum splits into at least one part, not {}", parts));
    if (least > most) eo::detail::library_error(fmt("split_sum's parts lie in {}..{}, which is empty", least, most));
    if (least < 0) eo::detail::library_error(fmt("split_sum's parts are at least 0, not {}", least));
    long long lowest = 0;
    long long highest = 0;
    if (eo::detail::product_overflows(least, parts, &lowest))
        eo::detail::library_error(fmt("{} parts of {}..{} add up to more than a long long holds, not {}", parts,
                                      least, most, total));
    bool const unbounded = eo::detail::product_overflows(most, parts, &highest);
    if (total < lowest || (!unbounded && total > highest))
        eo::detail::library_error(
            fmt("{} parts of {}..{} add up to {}..{}, not {}", parts, least, most, lowest, highest, total));
    long long const room = most - least;
    std::vector<long long> shares = draw.partition(parts, total - lowest, 0);
    long long spill = 0;
    for (long long& share : shares) {
        if (share <= room) continue;
        spill += share - room;
        share = room;
    }
    if (spill > 0) {
        std::vector<std::size_t> order(shares.size());
        for (std::size_t at = 0; at < order.size(); at++) order[at] = at;
        draw.shuffle(order);
        for (std::size_t const at : order) {
            long long const given = (std::min)(room - shares[at], spill);
            shares[at] += given;
            spill -= given;
        }
    }
    for (long long& share : shares) share += least;
    return shares;
}

}  // namespace shapes
}  // namespace eo

namespace eo {
namespace shapes {
namespace detail {

inline void room_for_elements(long long n, long long least, char const* what) {
    if (n < least) {
        if (least == 0) eo::detail::library_error(fmt("{} has at least no elements, not {}", what, n));
        eo::detail::library_error(fmt("{} needs at least {} elements, not {}", what, least, n));
    }
}

inline std::vector<int> joined_in_cycles(std::vector<int> const& order, std::vector<long long> const& lengths) {
    std::vector<int> images(order.size(), 0);
    std::size_t first = 0;
    for (long long const length : lengths) {
        std::size_t const last = first + static_cast<std::size_t>(length) - 1;
        for (std::size_t at = first; at < last; at++)
            images[static_cast<std::size_t>(order[at]) - 1] = order[at + 1];
        images[static_cast<std::size_t>(order[last]) - 1] = order[first];
        first = last + 1;
    }
    return images;
}

class ranked_values {
public:
    explicit ranked_values(int n) : counts_(static_cast<std::size_t>(n) + 1, 0) {
        while ((std::size_t{1} << (high_bit_ + 1)) <= static_cast<std::size_t>(n)) high_bit_++;
        for (std::size_t at = 1; at < counts_.size(); at++) {
            counts_[at]++;
            std::size_t const up = at + (at & (~at + 1));
            if (up < counts_.size()) counts_[up] += counts_[at];
        }
    }

    int take(long long rank) {
        std::size_t at = 0;
        for (int bit = high_bit_; bit >= 0; bit--) {
            std::size_t const next = at + (std::size_t{1} << bit);
            if (next < counts_.size() && counts_[next] <= rank) {
                at = next;
                rank -= counts_[next];
            }
        }
        for (std::size_t down = at + 1; down < counts_.size(); down += down & (~down + 1)) counts_[down]--;
        return static_cast<int>(at) + 1;
    }

private:
    std::vector<long long> counts_;
    int high_bit_ = 0;
};

inline std::vector<int> from_lehmer(std::vector<long long> const& code) {
    ranked_values left(static_cast<int>(code.size()));
    std::vector<int> values;
    values.reserve(code.size());
    for (long long const smaller_after : code) values.push_back(left.take(smaller_after));
    return values;
}

}  // namespace detail

[[nodiscard]] inline std::vector<int> permutation_cycles(rng& draw, int n, int k) {
    detail::room_for_elements(n, 1, "a permutation with cycles");
    if (k < 1 || k > n)
        eo::detail::library_error(fmt("a permutation of {} elements has 1..{} cycles, not {}", n, n, k));
    std::vector<long long> const lengths = draw.partition(k, n);
    return detail::joined_in_cycles(draw.perm(n, 1), lengths);
}

[[nodiscard]] inline std::vector<int> derangement(rng& draw, int n) {
    detail::room_for_elements(n, 0, "a derangement");
    if (n == 1) eo::detail::library_error("no derangement of 1 element exists; ask for 0 or at least 2");
    for (;;) {
        std::vector<int> p = draw.perm(n, 1);
        bool moved = true;
        for (int at = 0; at < n && moved; at++) moved = p[static_cast<std::size_t>(at)] != at + 1;
        if (moved) return p;
    }
}

[[nodiscard]] inline std::vector<int> involution(rng& draw, int n, int fixed) {
    detail::room_for_elements(n, 0, "an involution");
    if (fixed < 0 || fixed > n)
        eo::detail::library_error(
            fmt("an involution of {} elements has 0..{} fixed points, not {}", n, n, fixed));
    if ((n - fixed) % 2 != 0)
        eo::detail::library_error(
            fmt("an involution of {} elements pairs the other {}, which is odd; ask for an {} number of fixed points",
                n, n - fixed, n % 2 == 0 ? "even" : "odd"));
    std::vector<int> const order = draw.perm(n, 1);
    std::vector<int> images(static_cast<std::size_t>(n), 0);
    for (std::size_t at = 0; at < static_cast<std::size_t>(fixed); at++)
        images[static_cast<std::size_t>(order[at]) - 1] = order[at];
    for (std::size_t at = static_cast<std::size_t>(fixed); at < order.size(); at += 2) {
        images[static_cast<std::size_t>(order[at]) - 1] = order[at + 1];
        images[static_cast<std::size_t>(order[at + 1]) - 1] = order[at];
    }
    return images;
}

[[nodiscard]] inline std::vector<int> with_inversions(rng& draw, int n, long long k) {
    detail::room_for_elements(n, 1, "a permutation with inversions");
    long long room = static_cast<long long>(n) * (n - 1) / 2;
    if (k < 0 || k > room)
        eo::detail::library_error(fmt("a permutation of {} elements has 0..{} inversions, not {}", n, room, k));
    std::vector<long long> code(static_cast<std::size_t>(n), 0);
    for (int const at : draw.perm(n)) {
        long long const most = n - 1 - at;
        room -= most;
        long long const given = draw.uniform((std::max)(0LL, k - room), (std::min)(most, k));
        code[static_cast<std::size_t>(at)] = given;
        k -= given;
    }
    return detail::from_lehmer(code);
}

[[nodiscard]] inline std::vector<int> with_lis(rng& draw, int n, int k) {
    detail::room_for_elements(n, 1, "a permutation with a longest increasing subsequence");
    if (k < 1 || k > n)
        eo::detail::library_error(fmt(
            "the longest increasing subsequence of a permutation of {} elements is 1..{} long, not {}", n, n, k));
    std::vector<long long> const sizes = draw.partition(k, n);
    std::vector<int> owner;
    owner.reserve(static_cast<std::size_t>(n));
    for (int chain = 0; chain < k; chain++)
        owner.insert(owner.end(), static_cast<std::size_t>(sizes[static_cast<std::size_t>(chain)]), chain);
    draw.shuffle(owner);
    std::vector<int> last(static_cast<std::size_t>(k), 0);
    for (int at = 0; at < n; at++) last[static_cast<std::size_t>(owner[static_cast<std::size_t>(at)])] = at;
    std::vector<std::vector<int>> values(static_cast<std::size_t>(k));
    int lowest = 0;
    for (int at = 0; at < n; at++) {
        int const chain = owner[static_cast<std::size_t>(at)];
        if (last[static_cast<std::size_t>(chain)] == at) values[static_cast<std::size_t>(chain)].push_back(++lowest);
    }
    std::vector<int> rest;
    rest.reserve(static_cast<std::size_t>(n - k));
    for (int chain = 0; chain < k; chain++)
        rest.insert(rest.end(), static_cast<std::size_t>(sizes[static_cast<std::size_t>(chain)]) - 1, chain);
    draw.shuffle(rest);
    for (int const chain : rest) values[static_cast<std::size_t>(chain)].push_back(++lowest);
    std::vector<int> p;
    p.reserve(static_cast<std::size_t>(n));
    for (int const chain : owner) {
        std::vector<int>& mine = values[static_cast<std::size_t>(chain)];
        p.push_back(mine.back());
        mine.pop_back();
    }
    if (draw.chance(0.5)) {
        std::vector<int> turned(p.size(), 0);
        for (std::size_t at = 0; at < p.size(); at++) turned[p.size() - 1 - at] = n + 1 - p[at];
        p = std::move(turned);
    }
    if (draw.chance(0.5)) {
        std::vector<int> inverse(p.size(), 0);
        for (std::size_t at = 0; at < p.size(); at++)
            inverse[static_cast<std::size_t>(p[at]) - 1] = static_cast<int>(at) + 1;
        p = std::move(inverse);
    }
    return p;
}

[[nodiscard]] inline std::vector<int> permutation(rng& draw, int n, std::string const& shape) {
    detail::room_for_elements(n, 1, "a permutation");
    if (shape == "random") return draw.perm(n, 1);
    if (shape == "cycle") return permutation_cycles(draw, n, 1);
    if (shape == "derangement") return derangement(draw, n);
    if (shape == "involution") return involution(draw, n, n % 2);
    std::vector<int> ordered(static_cast<std::size_t>(n), 0);
    for (int at = 0; at < n; at++) ordered[static_cast<std::size_t>(at)] = at + 1;
    if (shape == "identity") return ordered;
    if (shape == "reversed") return std::vector<int>(ordered.rbegin(), ordered.rend());
    eo::detail::library_error(
        fmt("\"{}\" is not a permutation shape; the names are random, identity, reversed, cycle, derangement and "
            "involution",
            shape));
}

}  // namespace shapes
}  // namespace eo

namespace eo {
namespace shapes {
namespace detail {

inline void room_for_letters(long long length, char const* what) {
    if (length < 0) eo::detail::library_error(fmt("{} is at least empty, not {} long", what, length));
}

}  // namespace detail

[[nodiscard]] inline std::string repeated(char one, long long length) {
    detail::room_for_letters(length, "a repeated string");
    return std::string(static_cast<std::size_t>(length), one);
}

[[nodiscard]] inline std::string periodic(std::string const& unit, long long length) {
    detail::room_for_letters(length, "a periodic string");
    if (unit.empty()) eo::detail::library_error("a periodic string needs a unit to repeat");
    std::string out;
    out.reserve(static_cast<std::size_t>(length));
    while (static_cast<long long>(out.size()) < length)
        out.append(unit, 0, static_cast<std::size_t>(length) - out.size());
    return out;
}

[[nodiscard]] inline std::string near_periodic(rng& draw, std::string const& unit, long long length,
                                               charset const& allowed) {
    std::string out = periodic(unit, length);
    if (out.empty()) return out;
    std::size_t const spot = static_cast<std::size_t>(draw.uniform(0, static_cast<long long>(out.size()) - 1));
    std::vector<char> others;
    for (int one = 0; one < 256; one++) {
        char const letter = static_cast<char>(one);
        if (allowed.has(letter) && letter != out[spot]) others.push_back(letter);
    }
    if (others.empty())
        eo::detail::library_error(
            fmt("near_periodic needs a character other than '{}' in \"{}\"", out[spot], allowed.text()));
    out[spot] = draw.pick(others);
    return out;
}

[[nodiscard]] inline std::string fibonacci_word(long long length) {
    detail::room_for_letters(length, "a Fibonacci word");
    std::string older = "b";
    std::string newer = "a";
    while (static_cast<long long>(newer.size()) < length) {
        std::string next = newer + older;
        older = std::move(newer);
        newer = std::move(next);
    }
    newer.resize(static_cast<std::size_t>(length));
    return newer;
}

[[nodiscard]] inline std::string thue_morse(long long length) {
    detail::room_for_letters(length, "a Thue-Morse word");
    std::string out;
    out.reserve(static_cast<std::size_t>(length));
    for (long long at = 0; at < length; at++) {
        int ones = 0;
        for (unsigned long long bits = static_cast<unsigned long long>(at); bits != 0; bits >>= 1)
            ones += static_cast<int>(bits & 1u);
        out.push_back(ones % 2 == 0 ? 'a' : 'b');
    }
    return out;
}

[[nodiscard]] inline std::string palindrome(rng& draw, long long length, charset const& allowed) {
    detail::room_for_letters(length, "a palindrome");
    std::string out = draw.letters(length, allowed);
    for (long long at = 0; at * 2 < length; at++)
        out[static_cast<std::size_t>(length - 1 - at)] = out[static_cast<std::size_t>(at)];
    return out;
}

}  // namespace shapes
}  // namespace eo

namespace eo {

struct point {
    long long x;
    long long y;
};

namespace shapes {
namespace detail {

inline void room_for_points(long long count, long long limit, char const* what) {
    if (count < 0) eo::detail::library_error(fmt("{} has at least no points, not {}", what, count));
    if (limit < 1) eo::detail::library_error(fmt("{} needs a coordinate bound of at least 1, not {}", what, limit));
}

inline long long whole_root(long long square) {
    long long root = static_cast<long long>(std::sqrt(static_cast<double>(square)));
    while (root > 0 && root * root > square) root--;
    while ((root + 1) * (root + 1) <= square) root++;
    return root;
}

inline long long shared_divisor(long long left, long long right) {
    while (right != 0) {
        long long const next = left % right;
        left = right;
        right = next;
    }
    return left < 0 ? -left : left;
}

inline std::vector<long long> const& circle_radii() {
    static std::vector<long long> const ladder{5, 65, 1105, 32045, 1185665};
    return ladder;
}

inline std::vector<point> lattice_on(long long radius) {
    std::vector<point> found;
    for (long long x = -radius; x <= radius; x++) {
        long long const rest = radius * radius - x * x;
        long long const y = whole_root(rest);
        if (y * y != rest) continue;
        found.push_back(point{x, y});
        if (y != 0) found.push_back(point{x, -y});
    }
    return found;
}

inline int half_of(point const& step) {
    return step.y < 0 || (step.y == 0 && step.x < 0) ? 1 : 0;
}

inline std::vector<long long> chained(rng& draw, long long count, long long limit) {
    std::vector<long long> values = draw.distinct(count, 0, limit);
    std::sort(values.begin(), values.end());
    long long const least = values.front();
    long long const most = values.back();
    long long top = least;
    long long bottom = least;
    std::vector<long long> steps;
    for (std::size_t at = 1; at + 1 < values.size(); at++) {
        long long const here = values[at];
        if (draw.chance(0.5)) {
            steps.push_back(here - top);
            top = here;
        } else {
            steps.push_back(bottom - here);
            bottom = here;
        }
    }
    steps.push_back(most - top);
    steps.push_back(bottom - most);
    return steps;
}

}  // namespace detail

[[nodiscard]] inline std::vector<point> scattered(rng& draw, long long count, long long limit) {
    detail::room_for_points(count, limit, "a cloud of points");
    std::vector<point> made;
    made.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++)
        made.push_back(point{draw.uniform(-limit, limit), draw.uniform(-limit, limit)});
    return made;
}

[[nodiscard]] inline std::vector<point> collinear(rng& draw, long long count, long long limit) {
    detail::room_for_points(count, limit, "a line of points");
    if (count <= 1) return scattered(draw, count, limit);
    long long const steps = count - 1;
    long long const reach = 2 * limit / steps;
    if (reach < 1)
        eo::detail::library_error(
            fmt("{} different collinear points do not fit inside +-{}", count, limit));
    long long dx = 0;
    long long dy = 0;
    while (dx == 0 && dy == 0) {
        dx = draw.uniform(0, reach);
        dy = draw.uniform(-reach, reach);
    }
    long long const shared = detail::shared_divisor(dx, dy);
    dx /= shared;
    dy /= shared;
    long long const from_x = draw.uniform(-limit, limit - steps * dx);
    long long const from_y = dy >= 0 ? draw.uniform(-limit, limit - steps * dy)
                                     : draw.uniform(-limit - steps * dy, limit);
    std::vector<point> made;
    made.reserve(static_cast<std::size_t>(count));
    for (long long at = 0; at < count; at++) made.push_back(point{from_x + at * dx, from_y + at * dy});
    draw.shuffle(made);
    return made;
}

[[nodiscard]] inline std::vector<point> convex_position(rng& draw, long long count, long long limit) {
    detail::room_for_points(count, limit, "a convex polygon");
    if (count < 3) eo::detail::library_error(fmt("a convex polygon has at least 3 points, not {}", count));
    if (count > 2 * limit + 1)
        eo::detail::library_error(fmt("{} points in convex position do not fit inside +-{}", count, limit));
    if (limit > 1000000000)
        eo::detail::library_error(
            fmt("a convex polygon inside +-{} would overflow its own cross products; 1000000000 is the most",
                limit));
    std::vector<long long> across = detail::chained(draw, count, 2 * limit);
    std::vector<long long> upward = detail::chained(draw, count, 2 * limit);
    draw.shuffle(upward);
    std::vector<point> steps;
    steps.reserve(static_cast<std::size_t>(count));
    for (std::size_t at = 0; at < across.size(); at++) steps.push_back(point{across[at], upward[at]});
    std::sort(steps.begin(), steps.end(), [](point const& left, point const& right) {
        int const left_half = detail::half_of(left);
        int const right_half = detail::half_of(right);
        if (left_half != right_half) return left_half < right_half;
        long long const turn = left.x * right.y - left.y * right.x;
        if (turn != 0) return turn > 0;
        return std::tie(left.x, left.y) < std::tie(right.x, right.y);
    });
    std::vector<point> made;
    made.reserve(static_cast<std::size_t>(count));
    long long x = 0;
    long long y = 0;
    long long least_x = 0;
    long long least_y = 0;
    for (point const& one : steps) {
        made.push_back(point{x, y});
        x += one.x;
        y += one.y;
        least_x = (std::min)(least_x, x);
        least_y = (std::min)(least_y, y);
    }
    for (point& one : made) {
        one.x += -limit - least_x;
        one.y += -limit - least_y;
    }
    return made;
}

[[nodiscard]] inline std::vector<point> cocircular(rng& draw, long long count) {
    if (count < 0) eo::detail::library_error(fmt("a circle holds at least no points, not {}", count));
    for (long long const radius : detail::circle_radii()) {
        std::vector<point> found = detail::lattice_on(radius);
        if (static_cast<long long>(found.size()) < count) continue;
        draw.shuffle(found);
        found.resize(static_cast<std::size_t>(count));
        return found;
    }
    eo::detail::library_error(
        fmt("no circle of radius under 1200000 carries {} lattice points; convex_position scales instead",
            count));
}

[[nodiscard]] inline std::vector<point> cocircular(rng& draw, long long count, long long limit) {
    detail::room_for_points(count, limit, "a circle");
    for (long long const radius : detail::circle_radii()) {
        if (radius > limit) break;
        std::vector<point> found = detail::lattice_on(radius);
        if (static_cast<long long>(found.size()) < count) continue;
        draw.shuffle(found);
        found.resize(static_cast<std::size_t>(count));
        return found;
    }
    if (count <= 4) {
        std::vector<point> found = detail::lattice_on(1);
        draw.shuffle(found);
        found.resize(static_cast<std::size_t>(count));
        return found;
    }
    eo::detail::library_error(
        fmt("the circles cocircular draws from, of radius 1, 5, 65, 1105, 32045 and 1185665, have none of radius "
            "at most {} with {} lattice points; raise the limit, or ask for fewer",
            limit, count));
}

[[nodiscard]] inline std::vector<point> extreme_points(rng& draw, long long count, long long limit) {
    detail::room_for_points(count, limit, "points on the bound");
    if (count > 8 * limit)
        eo::detail::library_error(fmt("the edge of +-{} carries {} different points, not {}", limit,
                                      8 * limit, count));
    std::set<std::pair<long long, long long>> seen;
    std::vector<point> made;
    long long tries = 0;
    long long const most = 64 * count + 1000;
    while (static_cast<long long>(made.size()) < count) {
        detail::still_trying(tries, most, "that many different points on the bound");
        long long const along = draw.uniform(-limit, limit);
        long long const side = draw.uniform(0, 3);
        point const one = side == 0   ? point{along, -limit}
                          : side == 1 ? point{along, limit}
                          : side == 2 ? point{-limit, along}
                                      : point{limit, along};
        if (!seen.emplace(one.x, one.y).second) continue;
        made.push_back(one);
    }
    detail::kept_of(count, tries, "that many different points on the bound", eo::detail::site::here());
    return made;
}

}  // namespace shapes
}  // namespace eo

#if defined(_MSC_VER) && defined(__clang__)
#pragma clang diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif

#endif
#endif
