#!/usr/bin/env python3
import pathlib
import re
import sys

CORE = ["core.h", "fmt.h", "parse.h", "diag.h", "io.h", "read.h", "stream.h", "structure.h", "random.h", "summary.h", "role.h", "validate.h", "check.h", "interact.h", "phases.h", "control.h", "generate.h"]

SHAPES = ["shapes/present.h", "shapes/trees.h", "shapes/graphs.h", "shapes/sequences.h", "shapes/strings.h", "shapes/points.h"]

CORE_BANNER = """\
// eolymp.h {version} — a judging library for the Eolymp platform.
// https://github.com/eolymp/h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eolymp Academy LLC
//
// Validators, checkers, interactors, controllers and generators. The test
// shapes a generator draws from live in the companion eolymp-shapes.h, which
// the judge's C++ runtime carries beside this file.
//
// Generated from src/ by tools/amalgamate.py. Do not edit this file.
"""

SHAPES_BANNER = """\
// eolymp-shapes.h {version} — test shapes for eolymp.h generators.
// https://github.com/eolymp/h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eolymp Academy LLC
//
// Trees, graphs, sequences, strings and points, with the relabelling and
// shuffling a generator must not forget. Include it after eolymp.h; the judge's
// C++ runtime carries both files.
//
// Generated from src/shapes/ by tools/amalgamate.py. Do not edit this file.
"""

TARGETS = [
    ("eolymp.h", CORE, CORE_BANNER, "EOLYMP_H_INCLUDED", None),
    ("eolymp-shapes.h", SHAPES, SHAPES_BANNER, "EOLYMP_SHAPES_H_INCLUDED", '#include "eolymp.h"'),
]


def version_of(root: pathlib.Path) -> str:
    text = (root / "src" / "core.h").read_text()
    found = re.search(r'#define EOLYMP_H_VERSION "([^"]+)"', text)
    if not found:
        raise SystemExit("amalgamate: no EOLYMP_H_VERSION in src/core.h")
    return found.group(1)


def build(root: pathlib.Path, order, banner, guard, prelude) -> str:
    system_includes = []
    bodies = []
    for name in order:
        text = (root / "src" / name).read_text()
        kept = []
        for line in text.splitlines():
            if line.strip() == "#pragma once":
                continue
            if re.match(r'\s*#\s*include\s*"', line):
                continue
            include = re.match(r'\s*#\s*include\s*(<[^>]+>)', line)
            if include:
                if include.group(1) not in system_includes:
                    system_includes.append(include.group(1))
                continue
            kept.append(line)
        bodies.append("\n".join(kept).strip("\n"))
    out = [banner.format(version=version_of(root)), "", f"#ifndef {guard}", f"#define {guard}", ""]
    if prelude is not None:
        out.append(prelude)
        out.append("")
    out.extend("#include " + name for name in sorted(system_includes))
    out.append("")
    out.append("\n\n".join(bodies))
    out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    checking = len(sys.argv) > 1 and sys.argv[1] == "--check"
    stale = []
    for name, order, banner, guard, prelude in TARGETS:
        text = build(root, order, banner, guard, prelude)
        for target in (root / name, root / "judge" / "include" / name):
            if checking:
                if not target.exists() or target.read_text() != text:
                    stale.append(str(target.relative_to(root)))
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
    if stale:
        print(f"{', '.join(stale)} is out of date; run tools/amalgamate.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
