#!/usr/bin/env python3
import pathlib
import re
import sys

from common import ROOT
from version import Refused, current

CORE = ["core.h", "fmt.h", "parse.h", "diag.h", "os.h", "io.h", "read.h", "pattern.h", "stream.h", "structure.h", "random.h", "summary.h", "role.h", "validate.h", "check.h", "interact.h", "phases.h", "control.h", "generate.h"]

SHAPES = ["shapes/present.h", "shapes/trees.h", "shapes/graphs.h", "shapes/weighted.h", "shapes/sequences.h", "shapes/permutations.h", "shapes/intervals.h", "shapes/queries.h", "shapes/grids.h", "shapes/numbers.h", "shapes/strings.h", "shapes/points.h", "shapes/enumerate.h"]

CORE_BANNER = """\
// eolymp.h {version} — a judging library for the Eolymp platform.
// https://github.com/eolymp/h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eolymp Academy LLC
//
// Validators, checkers, interactors, controllers and generators. The test
// shapes a generator draws from live in the companion eolymp-shapes.h, which
// the judge's C++ runtime carries beside this file.
//
// Generated from src/ by tools/amalgamate.py. Do not edit this file.
"""

SHAPES_BANNER = """\
// eolymp-shapes.h {version} — test shapes for eolymp.h generators.
// https://github.com/eolymp/h
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eolymp Academy LLC
//
// Trees, graphs, sequences, strings and points, with the relabelling and
// shuffling a generator must not forget. Include it after eolymp.h; the judge's
// C++ runtime carries both files.
//
// Generated from src/shapes/ by tools/amalgamate.py. Do not edit this file.
"""

LANGUAGE = "(defined(_MSVC_LANG) ? _MSVC_LANG : __cplusplus)"

UNSAFE_SILENCED = """\
#if defined(_MSC_VER) && defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable : 4996)
#endif
"""

UNSAFE_RESTORED = """\
#if defined(_MSC_VER) && defined(__clang__)
#pragma clang diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif
"""

TOO_OLD = '#error "eolymp.h needs C++17 or later: build with -std=c++17"'

TARGETS = [
    ("eolymp.h", CORE, CORE_BANNER, "EOLYMP_H_INCLUDED", None, TOO_OLD),
    ("eolymp-shapes.h", SHAPES, SHAPES_BANNER, "EOLYMP_SHAPES_H_INCLUDED", '#include "eolymp.h"', None),
]


def build(root: pathlib.Path, version, order, banner, guard, prelude, too_old) -> str:
    system_includes = []
    bodies = []
    for name in order:
        text = (root / "src" / name).read_text()
        kept = []
        depth = 0
        for line in text.splitlines():
            if line.strip() == "#pragma once":
                continue
            if re.match(r'\s*#\s*include\s*"', line):
                continue
            if re.match(r'\s*#\s*if', line):
                depth += 1
            elif re.match(r'\s*#\s*endif', line):
                depth -= 1
            include = re.match(r'\s*#\s*include\s*(<[^>]+>)', line)
            if include and depth == 0:
                if include.group(1) not in system_includes:
                    system_includes.append(include.group(1))
                continue
            kept.append(line)
        bodies.append("\n".join(kept).strip("\n"))
    out = [banner.format(version=version), "", f"#ifndef {guard}", f"#define {guard}", ""]
    if prelude is not None:
        out.append(prelude)
        out.append("")
    if too_old is not None:
        out.extend([f"#if {LANGUAGE} < 201703L", too_old, "#else", ""])
    else:
        out.extend([f"#if {LANGUAGE} >= 201703L", ""])
    out.append(UNSAFE_SILENCED)
    out.extend("#include " + name for name in sorted(system_includes))
    out.append("")
    out.append("\n\n".join(bodies))
    out.append("")
    out.append(UNSAFE_RESTORED)
    out.append("#endif")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main() -> int:
    root = ROOT
    try:
        version = current()
    except Refused as reason:
        raise SystemExit(f"amalgamate: {reason}")
    checking = len(sys.argv) > 1 and sys.argv[1] == "--check"
    stale = []
    for name, order, banner, guard, prelude, too_old in TARGETS:
        text = build(root, version, order, banner, guard, prelude, too_old)
        for target in (root / name, root / "judge" / "include" / name):
            if checking:
                if not target.exists() or target.read_text() != text:
                    stale.append(str(target.relative_to(root)))
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
    if stale:
        print(f"{', '.join(stale)} is out of date; run tools/amalgamate.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
